name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          DECRYPTION_SECRET: ${{ secrets.DECRYPTION_SECRET }}

      - run: npm run eslint:quiet

  prettier:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          DECRYPTION_SECRET: ${{ secrets.DECRYPTION_SECRET }}

      - run: npm run prettier:check
